### ISSUE TITLE
UnboundLocalError: winSize referenced before assignment

### ISSUE THREAD

**Issue by stsmall** [bioXiaoheng/BalLeRMix#3]
Hi @bioXiaoheng,
I am running into the below error when running BalLeRMix. I read the issue where there were repeated genPos in the input file and I did have these, but I corrected them by incrementing the adjacent values that were the same. While that did seem to fix the error on one of my chromosomes and it ran to completion, I still got an error on the other two. I cloned the repo on Friday Feb 12th and am using python 3.8. 
thanks!
@stsmall

  File "BalLeRMix/software/BalLeRMix_v2.2.py", line 765, in <module>
    main()
  File "BalLeRMix/software/BalLeRMix_v2.2.py", line 757, in main
    scan(xGrid,AGrid,AdGrid,aGrid,opt.outfile,phys_pos,pos_list,Ks,Ns,numSites,Spec, logSpec, Fx,N, opt.size,opt.r,opt.step,opt.phys,opt.nofreq,opt.MAF,opt.noCenter,opt.Rrate)#, ProbsStar
  File "BalLeRMix/software/BalLeRMix_v2.2.py", line 629, in scan
    scan_alpha(xGrid,AGrid,AdGrid,aGrid,outfile,phys_pos,pos_list,Ks,Ns,numSites,Spec,logSpec,Fx,N,s,MAF)
  File "BalLeRMix/software/BalLeRMix_v2.2.py", line 596, in scan_alpha
    Tmax,winSites = calcBaller(pos_list, Ks, Ns, testSite, int(i), logSpec, Fx, xGrid, AGrid, AdGrid, aGrid, MAF)
  File "BalLeRMix/software/BalLeRMix_v2.2.py", line 508, in calcBaller
    return(Tmax,winSize)
UnboundLocalError: local variable 'winSize' referenced before assignment

**Comment by stsmall** [comment]
it seems that this is a similar issue to the one on Feb 2020. While the genPos is not the same the LR drop to almost 0.
37283490        169.8142        1.0978173902258277      0.65,0.35       10000   152
37283552        169.81420999999997      0.00020254474309666648  0.6,0.4 1e+06   4
37283559        169.81421999999998      0.0006828025218013067   0.5,0.5 1e+06   4
37283583        169.81422999999998      0.00020254475187186927  0.6,0.4 1e+06   4
37283723        169.81423999999998      0.0001831182677420884   0.55,0.45       1e+06   4
37283779        169.81425       0.0001542164327474893   0.8,0.2 1e+06   4
37283803        169.81426       6.535236756377572e-05   0.8,0.2 1e+06   4
37284014        169.81427       0.00012438855985408281  0.65,0.35       1e+06   4
37284017        169.81428       3.516538265557756e-05   0.85,0.15       1e+06   4
37284124        169.81429       0.0014568537759203082   0.7,0.3 1e+06   10

**Comment by bioXiaoheng** [comment]
Hi @stsmall , sorry for my belated reply. Can you share a sample input file to replicate the error? I made some fixes in the code (haven't committed to github yet) and want to see if the problem persists.

**Comment by stsmall** [comment]
Hi @bioXiaoheng,
thanks for the assistance. I attached a sample file that covers the same interval I listed above.
thanks,
@stsmall 
[3.f.b2.sample.input.gz](https://github.com/bioXiaoheng/BalLeRMix/files/6266564/3.f.b2.sample.input.gz)

**Comment by bioXiaoheng** [comment]
Thanks for sharing the file. Can you also share the spectrum file and the command line you used?

I noticed that the genetic positions in your input do not have the matching precision as your physical position. Does the problem persist after you fix this?


> Hi @bioXiaoheng,
> thanks for the assistance. I attached a sample file that covers the same interval I listed above.
> thanks,
> @stsmall
> [3.f.b2.sample.input.gz](https://github.com/bioXiaoheng/BalLeRMix/files/6266564/3.f.b2.sample.input.gz)

**Comment by stsmall** [comment]
yes, there the problem persists even with the added precision. Here are two file, spectrum and input file with increased precision.
[f.spect.gz](https://github.com/bioXiaoheng/BalLeRMix/files/6290793/f.spect.gz)
[3.f.b2.input.gz](https://github.com/bioXiaoheng/BalLeRMix/files/6290794/3.f.b2.input.gz)

**Comment by bioXiaoheng** [comment]
Hi @stsmall , can you share the command you used? I ran the B2 command on my end, and the script finished running without reporting errors.
[testout_issue3_v2.2.txt](https://github.com/bioXiaoheng/BalLeRMix/files/6292731/testout_issue3_v2.2.txt)

**Comment by bioXiaoheng** [comment]
@stsmall  I updated the script regardless. Still, let me know how to replicate your problem & test out the v2.3 to see if it persists.

**Comment by stsmall** [comment]
ah, sorry. I missed that comment. Thanks for the assist. I will try out the new version. Where can I find it? Is it on master or another branch?
thanks!

**Comment by bioXiaoheng** [comment]
@stsmall Oops, didn't realize the commit wasn't finalized till now. They should be up in software/ folder now; let me know whether they work for you. Also your command is the same one I used to generate the output file.

**Comment by stsmall** [comment]
Hi @bioXiaoheng,
I ran it to completion without error. Thank you very much for your help!
