### ISSUE TITLE
Integer/Float error?

### ISSUE THREAD

**Issue by YannBourgeois** [bioXiaoheng/BalLeRMix#4]
Dear Xiaoheng,
I was experimenting with BALLERMIX (v2.3), and had an issue when running the statistics based on the MAF (for example B0,MAF). I got Type errors such as "TypeError: 'float' object cannot be interpreted as an integer".
I think the error came from lines such as L73, 361, 364, where the result of a division (which is a float instead of an integer) was fed to the range() function. When replacing, for example L73:
_for i in range(N/2):_
by 
_for i in range(N//2):_
The error disappeared. I guess _range(int(N/2))_ would work too. 
My apologies if I missed something. Thanks for this resource, it is a really nice contribution!
All the best,
Yann Bourgeois

**Comment by bioXiaoheng** [comment]
Hi Yann,

Thank you so much for reporting this bug! This script was initially written in python2 where integer divisions would still return integers, and obviously when I upgraded it to python3 this was not accounted for. I can believe this went undetected for so long! I just fixed them in the v2.3 script. Thanks again for catching it!

Cheers,
Xiaoheng

**Comment by YannBourgeois** [comment]
Hi Xiaoheng,
No problem! I guess many people are lucky enough that they can confidently polarize alleles as ancestral/derived, so they do not have to fold their spectra :). 
Cheers,
Yann
