### ISSUE TITLE
error in scan_fixSize_siteCenter

### ISSUE THREAD

**Issue by deboraycb** [bioXiaoheng/BalLeRMix#7]
Hi, I think this line in the function for fixed window size in bp should have "w" instead of "r"
https://github.com/bioXiaoheng/BalLeRMix/blob/1972203935a80fbefdda0c6edf31dc78cefd6448/software/BalLeRMix_v2.3.py#L560

**Comment by bioXiaoheng** [comment]
Yes you're absolutely right! Thanks for catching the bug.
